
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author choco
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        int x,y;
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0,0, this.getBounds().width,this.getBounds().height,27,27);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttons2 = new u2c31.buttons();
        buttons3 = new u2c31.buttons();
        jPanel2 = new javax.swing.JPanel();
        buttons1 = new u2c31.buttons();
        buttons4 = new u2c31.buttons();
        buttons5 = new u2c31.buttons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 40, 51));

        buttons2.setBackground(new java.awt.Color(28, 40, 51));
        buttons2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_Subtract_20px_2.png"))); // NOI18N
        buttons2.setColorHover(new java.awt.Color(37, 52, 65));
        buttons2.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons2.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons2.setMaximumSize(new java.awt.Dimension(0, 0));
        buttons2.setMinimumSize(new java.awt.Dimension(0, 0));
        buttons2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons2ActionPerformed(evt);
            }
        });

        buttons3.setBackground(new java.awt.Color(28, 40, 51));
        buttons3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_Delete_20px_1.png"))); // NOI18N
        buttons3.setColorHover(new java.awt.Color(255, 0, 0));
        buttons3.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons3.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons3.setMaximumSize(new java.awt.Dimension(0, 0));
        buttons3.setMinimumSize(new java.awt.Dimension(0, 0));
        buttons3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttons2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttons3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttons3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(buttons2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(212, 212, 213));

        buttons1.setBackground(new java.awt.Color(28, 40, 51));
        buttons1.setText("Libros");
        buttons1.setColorHover(new java.awt.Color(37, 52, 65));
        buttons1.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons1.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons1ActionPerformed(evt);
            }
        });

        buttons4.setBackground(new java.awt.Color(28, 40, 51));
        buttons4.setText("Registrar prestamo");
        buttons4.setColorHover(new java.awt.Color(37, 52, 65));
        buttons4.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons4.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons4ActionPerformed(evt);
            }
        });

        buttons5.setBackground(new java.awt.Color(28, 40, 51));
        buttons5.setText("Donar un libro");
        buttons5.setColorHover(new java.awt.Color(37, 52, 65));
        buttons5.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons5.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttons4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttons5, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttons4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttons5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons1ActionPerformed
        panel cho = new panel();
       cho.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_buttons1ActionPerformed

    private void buttons4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons4ActionPerformed
        Formulario o = new Formulario();
       o.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_buttons4ActionPerformed

    private void buttons5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons5ActionPerformed
        Registro ho = new Registro();
       ho.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_buttons5ActionPerformed

    private void buttons2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons2ActionPerformed
             this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_buttons2ActionPerformed

    private void buttons3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons3ActionPerformed
        dispose();
    }//GEN-LAST:event_buttons3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private u2c31.buttons buttons1;
    private u2c31.buttons buttons2;
    private u2c31.buttons buttons3;
    private u2c31.buttons buttons4;
    private u2c31.buttons buttons5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
