
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author choco
 */
public class Registro extends javax.swing.JFrame {

    private Object Act;
    private Object AWTUtilities;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        int X,Y;
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0,0, this.getBounds().width,this.getBounds().height,27,27);
        
    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buttons15 = new u2c31.buttons();
        jLabel3 = new javax.swing.JLabel();
        buttons16 = new u2c31.buttons();
        buttons1 = new u2c31.buttons();
        buttons2 = new u2c31.buttons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(212, 212, 213));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Autor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jPanel8.setBackground(new java.awt.Color(28, 40, 51));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        buttons15.setBackground(new java.awt.Color(28, 40, 51));
        buttons15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_Delete_20px_1.png"))); // NOI18N
        buttons15.setColorHover(new java.awt.Color(255, 0, 0));
        buttons15.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons15.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons15.setMaximumSize(new java.awt.Dimension(0, 0));
        buttons15.setMinimumSize(new java.awt.Dimension(0, 0));
        buttons15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons15ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro");

        buttons16.setBackground(new java.awt.Color(28, 40, 51));
        buttons16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_Subtract_20px_2.png"))); // NOI18N
        buttons16.setColorHover(new java.awt.Color(37, 52, 65));
        buttons16.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons16.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons16.setMaximumSize(new java.awt.Dimension(0, 0));
        buttons16.setMinimumSize(new java.awt.Dimension(0, 0));
        buttons16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttons16MouseClicked(evt);
            }
        });
        buttons16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(220, 220, 220)
                .addComponent(buttons16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttons15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttons15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(buttons16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        buttons1.setBackground(new java.awt.Color(28, 40, 51));
        buttons1.setText("Volver");
        buttons1.setColorHover(new java.awt.Color(37, 52, 65));
        buttons1.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons1.setColorPressed(new java.awt.Color(28, 40, 51));
        buttons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 80, -1));

        buttons2.setBackground(new java.awt.Color(28, 40, 51));
        buttons2.setText("Registrar");
        buttons2.setColorHover(new java.awt.Color(37, 52, 65));
        buttons2.setColorNormal(new java.awt.Color(28, 40, 51));
        buttons2.setColorPressed(new java.awt.Color(28, 40, 51));
        jPanel1.add(buttons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttons16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttons16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttons16MouseClicked

    private void buttons16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons16ActionPerformed
        this.setState(Registro.ICONIFIED);
    }//GEN-LAST:event_buttons16ActionPerformed

    private void buttons15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons15ActionPerformed
        dispose();
    }//GEN-LAST:event_buttons15ActionPerformed

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void buttons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons1ActionPerformed
         Inicio cho = new Inicio();
       cho.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_buttons1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private u2c31.buttons buttons1;
    private u2c31.buttons buttons15;
    private u2c31.buttons buttons16;
    private u2c31.buttons buttons2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
